### PR TITLE
Support Vietnamese

### PR DESCRIPTION
**Pull request by tri2820**

### CODE REVIEW

**Comment by kuraydev** [comment]
Hello @tri2820 

In this PR, there are 68 file changes and the PR's title is just support Vietnamese. Can you please clean it up?

**Comment by kuraydev** [comment]
@tri2820 
I believe all you need are 
- `lib/utils/translations/index.ts`
- `lib/utils/translations/vi.ts`

these files, if you believe we need other changes as well you should open up another PR for these and explain, please :) 

Also, we should not have `build/dist` folders and files because these should be generated

**Comment by tri2820** [comment]
Sure, I built the files and committed them accidentally. Other than the 2 files however there is a fix needed to make Vietnamese work - I will create a PR and explain there.

**Comment by kuraydev** [comment]
@tri2820 
You should open another PR for the fixes then :)

**Pull request closed without merging**
